/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.migestion.ui.swing.balances;

import java.text.DecimalFormat;
import java.util.Date;

import com.migestion.model.Balance;
import com.migestion.swing.controller.exception.ControllerException;
import com.migestion.swing.navigation.interfaces.ILinkWindowOpen;
import com.migestion.swing.utils.UbicacionVentana;
import com.migestion.swing.view.dialogs.DialogMessage;
import com.migestion.swing.view.frames.JFrameContainer;
import com.migestion.ui.service.UIBalanceService;
import com.migestion.ui.service.UIServiceFactory;

/**
 *
 * @author bernardo
 */
public class DialogBalanceDiario extends javax.swing.JDialog implements ILinkWindowOpen {

    /**
     * Creates new form DialogBalanceDiario
     */
    public DialogBalanceDiario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pickerFecha = new com.toedter.calendar.JDateChooser(new Date());
        lblFecha = new javax.swing.JLabel();
        lblCaja = new javax.swing.JLabel();
        txtDebeCaja = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtDebeBancos = new javax.swing.JLabel();
        lblCheque = new javax.swing.JLabel();
        txtDebeCheque = new javax.swing.JLabel();
        txtHaberCaja = new javax.swing.JLabel();
        txtSaldoCaja = new javax.swing.JLabel();
        txtHaberBancos = new javax.swing.JLabel();
        txtSaldoBancos = new javax.swing.JLabel();
        txtHaberCheques = new javax.swing.JLabel();
        txtSaldoCheques = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDebeTotales = new javax.swing.JLabel();
        txtHaberTotales = new javax.swing.JLabel();
        txtSaldoTotales = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        lblCheque1 = new javax.swing.JLabel();
        txtDebeNotaCredito = new javax.swing.JLabel();
        txtHaberNotaCredito = new javax.swing.JLabel();
        txtSaldoNotaCredito = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pickerFecha.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                pickerFechaPropertyChange(evt);
            }
        });

        lblFecha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFecha.setText("Fecha");

        lblCaja.setFont(new java.awt.Font("Ubuntu", 2, 15)); // NOI18N
        lblCaja.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCaja.setText("Caja");

        txtDebeCaja.setBackground(java.awt.Color.white);
        txtDebeCaja.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtDebeCaja.setText("0.00");
        txtDebeCaja.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtDebeCaja.setOpaque(true);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 2, 15)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Bancos");

        txtDebeBancos.setBackground(java.awt.Color.white);
        txtDebeBancos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtDebeBancos.setText("0.00");
        txtDebeBancos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtDebeBancos.setOpaque(true);

        lblCheque.setFont(new java.awt.Font("Ubuntu", 2, 15)); // NOI18N
        lblCheque.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCheque.setText("Cheques");

        txtDebeCheque.setBackground(java.awt.Color.white);
        txtDebeCheque.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtDebeCheque.setText("0.00");
        txtDebeCheque.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtDebeCheque.setOpaque(true);

        txtHaberCaja.setBackground(java.awt.Color.white);
        txtHaberCaja.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtHaberCaja.setText("0.00");
        txtHaberCaja.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtHaberCaja.setOpaque(true);

        txtSaldoCaja.setBackground(java.awt.Color.white);
        txtSaldoCaja.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtSaldoCaja.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtSaldoCaja.setText("0.00");
        txtSaldoCaja.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSaldoCaja.setOpaque(true);

        txtHaberBancos.setBackground(java.awt.Color.white);
        txtHaberBancos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtHaberBancos.setText("0.00");
        txtHaberBancos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtHaberBancos.setOpaque(true);

        txtSaldoBancos.setBackground(java.awt.Color.white);
        txtSaldoBancos.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtSaldoBancos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtSaldoBancos.setText("0.00");
        txtSaldoBancos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSaldoBancos.setOpaque(true);

        txtHaberCheques.setBackground(java.awt.Color.white);
        txtHaberCheques.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtHaberCheques.setText("0.00");
        txtHaberCheques.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtHaberCheques.setOpaque(true);

        txtSaldoCheques.setBackground(java.awt.Color.white);
        txtSaldoCheques.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtSaldoCheques.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtSaldoCheques.setText("0.00");
        txtSaldoCheques.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSaldoCheques.setOpaque(true);

        jLabel2.setBackground(new java.awt.Color(236, 222, 174));
        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Debe");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel2.setOpaque(true);

        jLabel3.setBackground(new java.awt.Color(236, 222, 174));
        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Haber");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel3.setOpaque(true);

        jLabel4.setBackground(new java.awt.Color(236, 222, 174));
        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Saldo");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel4.setOpaque(true);

        jLabel5.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        jLabel5.setText("Totales");

        txtDebeTotales.setBackground(java.awt.Color.white);
        txtDebeTotales.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtDebeTotales.setText("0.00");
        txtDebeTotales.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtDebeTotales.setOpaque(true);

        txtHaberTotales.setBackground(java.awt.Color.white);
        txtHaberTotales.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtHaberTotales.setText("0.00");
        txtHaberTotales.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtHaberTotales.setOpaque(true);

        txtSaldoTotales.setBackground(java.awt.Color.white);
        txtSaldoTotales.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtSaldoTotales.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtSaldoTotales.setText("0.00");
        txtSaldoTotales.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSaldoTotales.setOpaque(true);

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        lblCheque1.setFont(new java.awt.Font("Ubuntu", 2, 15)); // NOI18N
        lblCheque1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCheque1.setText("Notas de crédito");

        txtDebeNotaCredito.setBackground(java.awt.Color.white);
        txtDebeNotaCredito.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtDebeNotaCredito.setText("0.00");
        txtDebeNotaCredito.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtDebeNotaCredito.setOpaque(true);

        txtHaberNotaCredito.setBackground(java.awt.Color.white);
        txtHaberNotaCredito.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtHaberNotaCredito.setText("0.00");
        txtHaberNotaCredito.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtHaberNotaCredito.setOpaque(true);

        txtSaldoNotaCredito.setBackground(java.awt.Color.white);
        txtSaldoNotaCredito.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtSaldoNotaCredito.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtSaldoNotaCredito.setText("0.00");
        txtSaldoNotaCredito.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSaldoNotaCredito.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(lblCheque)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblFecha)
                                .addComponent(lblCaja, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblCheque1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                            .addComponent(txtDebeCheque, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDebeBancos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDebeCaja, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDebeTotales, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pickerFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDebeNotaCredito, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtHaberBancos, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSaldoBancos, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtHaberCheques, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSaldoCheques, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                    .addComponent(txtHaberCaja, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSaldoCaja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtHaberTotales, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSaldoTotales, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtHaberNotaCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSaldoNotaCredito, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCerrar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(pickerFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFecha))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCaja)
                    .addComponent(txtDebeCaja)
                    .addComponent(txtHaberCaja)
                    .addComponent(txtSaldoCaja))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDebeBancos)
                    .addComponent(txtHaberBancos)
                    .addComponent(txtSaldoBancos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCheque)
                    .addComponent(txtDebeCheque)
                    .addComponent(txtHaberCheques)
                    .addComponent(txtSaldoCheques))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCheque1)
                    .addComponent(txtDebeNotaCredito)
                    .addComponent(txtHaberNotaCredito)
                    .addComponent(txtSaldoNotaCredito))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDebeTotales)
                    .addComponent(txtHaberTotales)
                    .addComponent(txtSaldoTotales))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(btnCerrar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void pickerFechaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_pickerFechaPropertyChange
        // TODO add your handling code here:
        doCalcularSaldos();
    }//GEN-LAST:event_pickerFechaPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogBalanceDiario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogBalanceDiario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogBalanceDiario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogBalanceDiario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogBalanceDiario dialog = new DialogBalanceDiario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblCaja;
    private javax.swing.JLabel lblCheque;
    private javax.swing.JLabel lblCheque1;
    private javax.swing.JLabel lblFecha;
    private com.toedter.calendar.JDateChooser pickerFecha;
    private javax.swing.JLabel txtDebeBancos;
    private javax.swing.JLabel txtDebeCaja;
    private javax.swing.JLabel txtDebeCheque;
    private javax.swing.JLabel txtDebeNotaCredito;
    private javax.swing.JLabel txtDebeTotales;
    private javax.swing.JLabel txtHaberBancos;
    private javax.swing.JLabel txtHaberCaja;
    private javax.swing.JLabel txtHaberCheques;
    private javax.swing.JLabel txtHaberNotaCredito;
    private javax.swing.JLabel txtHaberTotales;
    private javax.swing.JLabel txtSaldoBancos;
    private javax.swing.JLabel txtSaldoCaja;
    private javax.swing.JLabel txtSaldoCheques;
    private javax.swing.JLabel txtSaldoNotaCredito;
    private javax.swing.JLabel txtSaldoTotales;
    // End of variables declaration//GEN-END:variables

    private void doCalcularSaldos() {

    	Balance balanceCajas = new Balance();
    	Balance balanceBancos = new Balance();
    	Balance balanceCheques = new Balance();
    	Balance balanceNotasCredito = new Balance();
    	Balance balanceTotales = new Balance();
    	
    	Date fecha = pickerFecha.getDate();
    	
    	UIBalanceService service = UIServiceFactory.getUIBalanceService();
    	
    	try {
			
    		balanceCajas = service.getBalanceCajas( fecha );
    		balanceBancos = service.getBalanceBancos( fecha );
    		balanceCheques = service.getBalanceCheques( fecha );
    		balanceNotasCredito = service.getBalanceNotasCredito( fecha );
    		
    	} catch (ControllerException e) {
			
			DialogMessage.showErrorMessage( getTitle() , "Error obteniendo balance diario");
		}
    	
    	balanceTotales.setCantidadMovimientos( 
    			balanceBancos.getCantidadMovimientos()
    			+ balanceCheques.getCantidadMovimientos()
    			+ balanceCajas.getCantidadMovimientos()
    			+ balanceNotasCredito.getCantidadMovimientos() );
    	
    	balanceTotales.setDebe( 
    			balanceBancos.getDebe()
    			+ balanceCheques.getDebe()
    			+ balanceCajas.getDebe()
    			+ balanceNotasCredito.getDebe() );
    	
    	balanceTotales.setHaber( 
    			balanceBancos.getHaber()
    			+ balanceCheques.getHaber()
    			+ balanceCajas.getHaber()
    			+ balanceNotasCredito.getHaber() );
    	
    	DecimalFormat format = new java.text.DecimalFormat("$#0.00");
		
    	txtDebeCaja.setText(format.format( balanceCajas.getDebe() ));
    	txtDebeBancos.setText(format.format( balanceBancos.getDebe() ));
    	txtDebeCheque.setText(format.format( balanceCheques.getDebe() ));
    	txtDebeNotaCredito.setText(format.format( balanceNotasCredito.getDebe() ));
    	txtDebeTotales.setText(format.format( balanceTotales.getDebe() ));

    	txtHaberCaja.setText(format.format( balanceCajas.getHaber() ));
    	txtHaberBancos.setText(format.format( balanceBancos.getHaber() ));
    	txtHaberCheques.setText(format.format( balanceCheques.getHaber() ));
    	txtHaberNotaCredito.setText(format.format( balanceNotasCredito.getHaber() ));
    	txtHaberTotales.setText(format.format( balanceTotales.getHaber() ));

    	txtSaldoCaja.setText(format.format( balanceCajas.getSaldo() ));
    	txtSaldoBancos.setText(format.format( balanceBancos.getSaldo() ));
    	txtSaldoCheques.setText(format.format( balanceCheques.getSaldo() ));
    	txtSaldoNotaCredito.setText(format.format( balanceNotasCredito.getSaldo() ));
    	txtSaldoTotales.setText(format.format( balanceTotales.getSaldo() ));

    }

	public void open() {
		UbicacionVentana.centrar(this, false);
		clearInputs();
		this.setVisible(true);
	}

	private void clearInputs() {
		// TODO Auto-generated method stub
		
	}

	public void addToJFrameContainer(JFrameContainer container) {
		// TODO Auto-generated method stub
		
	}
}
