/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.migestion.ui.swing.proveedores.panel;

import java.awt.Container;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import com.migestion.model.CondicionIVA;
import com.migestion.model.Proveedor;
import com.migestion.model.TipoDocumento;
import com.migestion.swing.custom.ComboEnumElement;
import com.migestion.swing.custom.ComboModel;
import com.migestion.swing.view.dialogs.adapters.IDialogAddAdapter;
import com.migestion.swing.view.dialogs.adapters.IDialogDeleteAdapter;
import com.migestion.swing.view.dialogs.adapters.IDialogUpdateAdapter;
import com.migestion.swing.view.dialogs.adapters.IDialogViewAdapter;
import com.migestion.swing.view.exceptions.ViewException;
import com.migestion.swing.view.inputs.InputRequiredValidator;
import com.migestion.swing.view.inputs.InputValidator;
import com.migestion.swing.view.inputs.JTextFieldInspector;
import com.migestion.ui.swing.i18n.I18nMessages;

/**
 *
 * @author bernardo
 */
public class ProveedorPanel extends javax.swing.JPanel  implements Serializable, IDialogAddAdapter, IDialogUpdateAdapter, IDialogViewAdapter, IDialogDeleteAdapter{

    private InputRequiredValidator required;
    
    private Proveedor proveedor;

    /**
     * Creates new form ProveedorPanel
     */
    public ProveedorPanel() {
    	
    	initProveedor();
    	
        initComponents();
        
        initValidators();
        
		loadCombos();
				
    }

    private void initProveedor() {
		this.proveedor = new Proveedor();
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane = new javax.swing.JTabbedPane();
        jPanelDatosPersonales = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        lblFijo = new javax.swing.JLabel();
        txtTelefonoFijo = new javax.swing.JTextField();
        txtMovil = new javax.swing.JTextField();
        lblCelular = new javax.swing.JLabel();
        lblDomicilio = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDomicilio = new javax.swing.JTextArea();
        lblTipoDoc = new javax.swing.JLabel();
        cmbTipoDoc = new javax.swing.JComboBox();
        lblNroDoc = new javax.swing.JLabel();
        txtNroDoc = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblContacto = new javax.swing.JLabel();
        txtContacto = new javax.swing.JTextField();
        lblFechaNacimiento = new javax.swing.JLabel();
        lblTipoProveedor = new javax.swing.JLabel();
        cmbTipoProveedor = new javax.swing.JComboBox();
        pickerNacimiento = new com.toedter.calendar.JDateChooser();
        jPanelFacturacion = new javax.swing.JPanel();
        lblCUIT = new javax.swing.JLabel();
        txtCUIT = new javax.swing.JTextField();
        lblCondicionIVA = new javax.swing.JLabel();
        cmbCondicionIVA = new javax.swing.JComboBox();
        lblDomicilioFacturacion = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDomicilioFacturacion = new javax.swing.JTextArea();
        chkCuentaCorriente = new javax.swing.JCheckBox();
        txtDescubierto = new javax.swing.JFormattedTextField();
        lblDescubierto = new javax.swing.JLabel();
        jPanelSocial = new javax.swing.JPanel();
        lblFacebook = new javax.swing.JLabel();
        txtFacebook = new javax.swing.JTextField();
        lblWeb = new javax.swing.JLabel();
        txtWeb = new javax.swing.JTextField();
        txtTwitter = new javax.swing.JTextField();
        txtLinkedin = new javax.swing.JTextField();
        lblTwitter = new javax.swing.JLabel();
        lblLinkedin = new javax.swing.JLabel();
        jPanelObservaciones = new javax.swing.JPanel();
        jScrollPaneObservaciones = new javax.swing.JScrollPane();
        txtObservaciones = new javax.swing.JTextArea();

        setMinimumSize(new java.awt.Dimension(596, 400));
        setPreferredSize(new java.awt.Dimension(700, 450));
        setLayout(new java.awt.GridLayout(1, 0));

        txtNombre.setText("jTextField1");

        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombre.setText("Nombre");

        lblFijo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFijo.setText("Teléfono");

        txtTelefonoFijo.setText("jTextField2");

        txtMovil.setText("jTextField3");

        lblCelular.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCelular.setText("Celular");

        lblDomicilio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDomicilio.setText("Domicilio");
        lblDomicilio.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        txtDomicilio.setColumns(20);
        txtDomicilio.setRows(5);
        jScrollPane1.setViewportView(txtDomicilio);

        lblTipoDoc.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTipoDoc.setText("Tipo documento");

        cmbTipoDoc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbTipoDoc.setMinimumSize(new java.awt.Dimension(50, 28));
        cmbTipoDoc.setPreferredSize(new java.awt.Dimension(50, 28));

        lblNroDoc.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNroDoc.setText("Nro");

        txtNroDoc.setText("jTextField1");
        txtNroDoc.setMinimumSize(new java.awt.Dimension(100, 28));
        txtNroDoc.setPreferredSize(new java.awt.Dimension(100, 28));

        lblEmail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEmail.setText("Email");

        txtEmail.setText("jTextField1");

        lblContacto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblContacto.setText("Contacto");

        txtContacto.setText("jTextField1");

        lblFechaNacimiento.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFechaNacimiento.setText("Fecha de nacimiento");

        lblTipoProveedor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTipoProveedor.setText("Tipo de proveedor");

        cmbTipoProveedor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanelDatosPersonalesLayout = new javax.swing.GroupLayout(jPanelDatosPersonales);
        jPanelDatosPersonales.setLayout(jPanelDatosPersonalesLayout);
        jPanelDatosPersonalesLayout.setHorizontalGroup(
            jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosPersonalesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosPersonalesLayout.createSequentialGroup()
                        .addComponent(lblTipoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbTipoProveedor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelDatosPersonalesLayout.createSequentialGroup()
                        .addComponent(lblFijo, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelDatosPersonalesLayout.createSequentialGroup()
                        .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre))
                    .addGroup(jPanelDatosPersonalesLayout.createSequentialGroup()
                        .addGroup(jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmail)
                            .addGroup(jPanelDatosPersonalesLayout.createSequentialGroup()
                                .addComponent(cmbTipoDoc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(lblNroDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNroDoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanelDatosPersonalesLayout.createSequentialGroup()
                        .addComponent(lblContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtContacto))
                    .addGroup(jPanelDatosPersonalesLayout.createSequentialGroup()
                        .addComponent(lblFechaNacimiento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pickerNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelDatosPersonalesLayout.createSequentialGroup()
                        .addGroup(jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCelular, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDomicilio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelDatosPersonalesLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE))
                            .addGroup(jPanelDatosPersonalesLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTelefonoFijo)
                                    .addComponent(txtMovil))))))
                .addContainerGap())
        );
        jPanelDatosPersonalesLayout.setVerticalGroup(
            jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosPersonalesLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosPersonalesLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(lblFijo))
                    .addComponent(txtTelefonoFijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMovil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCelular))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDomicilio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNroDoc)
                    .addComponent(cmbTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNroDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTipoDoc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail))
                .addGap(5, 5, 5)
                .addGroup(jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblContacto))
                .addGap(5, 5, 5)
                .addGroup(jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pickerNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFechaNacimiento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosPersonalesLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(lblTipoProveedor))
                    .addComponent(cmbTipoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jTabbedPane.addTab("Datos personales", jPanelDatosPersonales);

        lblCUIT.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCUIT.setText("CUIT");

        txtCUIT.setText("jTextField1");

        lblCondicionIVA.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCondicionIVA.setText("Condición IVA");

        cmbCondicionIVA.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbCondicionIVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCondicionIVAActionPerformed(evt);
            }
        });

        lblDomicilioFacturacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDomicilioFacturacion.setText("Domicilio");

        txtDomicilioFacturacion.setColumns(20);
        txtDomicilioFacturacion.setRows(5);
        jScrollPane2.setViewportView(txtDomicilioFacturacion);

        chkCuentaCorriente.setText("Permitir cuenta corriente");

        txtDescubierto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtDescubierto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        lblDescubierto.setText("Saldo al descubierto");

        javax.swing.GroupLayout jPanelFacturacionLayout = new javax.swing.GroupLayout(jPanelFacturacion);
        jPanelFacturacion.setLayout(jPanelFacturacionLayout);
        jPanelFacturacionLayout.setHorizontalGroup(
            jPanelFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFacturacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFacturacionLayout.createSequentialGroup()
                        .addComponent(lblCUIT, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtCUIT))
                    .addGroup(jPanelFacturacionLayout.createSequentialGroup()
                        .addComponent(lblCondicionIVA, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbCondicionIVA, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelFacturacionLayout.createSequentialGroup()
                        .addGroup(jPanelFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDomicilioFacturacion, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDescubierto))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                            .addGroup(jPanelFacturacionLayout.createSequentialGroup()
                                .addGroup(jPanelFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkCuentaCorriente)
                                    .addComponent(txtDescubierto, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanelFacturacionLayout.setVerticalGroup(
            jPanelFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFacturacionLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanelFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCUIT)
                    .addComponent(txtCUIT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCondicionIVA)
                    .addComponent(cmbCondicionIVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDomicilioFacturacion)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkCuentaCorriente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescubierto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescubierto))
                .addContainerGap())
        );

        jTabbedPane.addTab("Facturación", jPanelFacturacion);

        lblFacebook.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFacebook.setText("Facebook");

        txtFacebook.setText("jTextField1");

        lblWeb.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblWeb.setText("Página web");

        txtWeb.setText("jTextField1");

        txtTwitter.setText("jTextField1");

        txtLinkedin.setText("jTextField1");

        lblTwitter.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTwitter.setText("Twitter");

        lblLinkedin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblLinkedin.setText("Linkedin");

        javax.swing.GroupLayout jPanelSocialLayout = new javax.swing.GroupLayout(jPanelSocial);
        jPanelSocial.setLayout(jPanelSocialLayout);
        jPanelSocialLayout.setHorizontalGroup(
            jPanelSocialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSocialLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanelSocialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTwitter, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLinkedin, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWeb, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFacebook, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelSocialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLinkedin, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                    .addComponent(txtTwitter)
                    .addComponent(txtWeb)
                    .addComponent(txtFacebook, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanelSocialLayout.setVerticalGroup(
            jPanelSocialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSocialLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanelSocialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFacebook)
                    .addComponent(txtFacebook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSocialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTwitter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTwitter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSocialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLinkedin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLinkedin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSocialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtWeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWeb))
                .addGap(278, 278, 278))
        );

        jTabbedPane.addTab("Social media", jPanelSocial);

        jPanelObservaciones.setLayout(new java.awt.BorderLayout());

        txtObservaciones.setColumns(20);
        txtObservaciones.setRows(5);
        jScrollPaneObservaciones.setViewportView(txtObservaciones);

        jPanelObservaciones.add(jScrollPaneObservaciones, java.awt.BorderLayout.CENTER);

        jTabbedPane.addTab("Observaciones", jPanelObservaciones);

        add(jTabbedPane);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbCondicionIVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCondicionIVAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCondicionIVAActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkCuentaCorriente;
    private javax.swing.JComboBox cmbCondicionIVA;
    private javax.swing.JComboBox cmbTipoProveedor;
    private javax.swing.JComboBox cmbTipoDoc;
    private javax.swing.JPanel jPanelDatosPersonales;
    private javax.swing.JPanel jPanelFacturacion;
    private javax.swing.JPanel jPanelObservaciones;
    private javax.swing.JPanel jPanelSocial;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPaneObservaciones;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JLabel lblCUIT;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblCondicionIVA;
    private javax.swing.JLabel lblContacto;
    private javax.swing.JLabel lblDescubierto;
    private javax.swing.JLabel lblDomicilio;
    private javax.swing.JLabel lblDomicilioFacturacion;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFacebook;
    private javax.swing.JLabel lblFechaNacimiento;
    private javax.swing.JLabel lblFijo;
    private javax.swing.JLabel lblLinkedin;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNroDoc;
    private javax.swing.JLabel lblTipoProveedor;
    private javax.swing.JLabel lblTipoDoc;
    private javax.swing.JLabel lblTwitter;
    private javax.swing.JLabel lblWeb;
    private com.toedter.calendar.JDateChooser pickerNacimiento;
    private javax.swing.JTextField txtCUIT;
    private javax.swing.JTextField txtContacto;
    private javax.swing.JFormattedTextField txtDescubierto;
    private javax.swing.JTextArea txtDomicilio;
    private javax.swing.JTextArea txtDomicilioFacturacion;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFacebook;
    private javax.swing.JTextField txtLinkedin;
    private javax.swing.JTextField txtMovil;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNroDoc;
    private javax.swing.JTextArea txtObservaciones;
    private javax.swing.JTextField txtTelefonoFijo;
    private javax.swing.JTextField txtTwitter;
    private javax.swing.JTextField txtWeb;
    // End of variables declaration//GEN-END:variables

	public Container getDeleteMsgPanel() {
		
		this.setEditable( false );
		
		return this;
	}

	public Container getViewPanel() {
		
		this.setEditable( false );
		
		return this;
	}
	
	public void setEditable( Boolean editable ){
		
		txtNombre.setEditable( false );
		
	}

	public void showObject(Object object) {
		
		clearInputs();
		
		proveedor = (Proveedor)object;
		txtNombre.setText( proveedor.getNombre() );
		
		txtDomicilio.setText( proveedor.getDomicilio() );
		txtEmail.setText( proveedor.getEmail() );
		txtContacto.setText( proveedor.getContacto() );

		txtTelefonoFijo.setText( proveedor.getTelefonoFijo() );
		txtMovil.setText( proveedor.getTelefonoMovil() );
		
		pickerNacimiento.setDate( proveedor.getFechaNacimiento() );
		
		chkCuentaCorriente.setSelected( proveedor.getTieneCtaCte() );
		txtDescubierto.setValue( proveedor.getDescubierto() );
		
		if(proveedor.getTipoDocumento()!=null){
			ComboEnumElement tipoDoc = new ComboEnumElement(proveedor.getTipoDocumento(), I18nMessages.locale(proveedor.getTipoDocumento().getNombre()));
			cmbTipoDoc.setSelectedItem( tipoDoc );	
		}
		
		
		if( proveedor.getNroDocumento()!=null)
			txtNroDoc.setText( proveedor.getNroDocumento().toString() );
		else
			txtNroDoc.setText("");

		txtCUIT.setText( proveedor.getCuit() );
		ComboEnumElement condicion = new ComboEnumElement(proveedor.getCondicionIVA(), I18nMessages.locale(proveedor.getCondicionIVA().getNombre()));
		cmbCondicionIVA.setSelectedItem( condicion );
		txtDomicilioFacturacion.setText( proveedor.getDomicilioFacturacion() );
		txtObservaciones.setText( proveedor.getObservaciones() );
		
		txtFacebook.setText( proveedor.getFacebook() );
		txtTwitter.setText( proveedor.getTwitter() );
		txtLinkedin.setText( proveedor.getLinkedin() );
		txtWeb.setText( proveedor.getPaginaWeb() );
		
		
	}

	public Container getInputPanel() {
		return this;
	}

	public Object getObjectFromUI() throws ViewException {
		
		proveedor.setNombre( txtNombre.getText() );
		proveedor.setTelefonoFijo( txtTelefonoFijo.getText() );
		proveedor.setTelefonoMovil( txtMovil.getText() );
		proveedor.setDomicilio( txtDomicilio.getText() );
		proveedor.setContacto( txtContacto.getText() );
		proveedor.setEmail( txtEmail.getText() );
		
		//TODO chequear que sea un número.
		if(txtNroDoc.getText().length()>0)
			proveedor.setNroDocumento( new Long(txtNroDoc.getText()) );

		proveedor.setTipoDocumento( (TipoDocumento)(((ComboEnumElement)cmbTipoDoc.getSelectedItem()).getItem()) );
		proveedor.setFechaNacimiento( pickerNacimiento.getDate() );
		
		proveedor.setCondicionIVA( (CondicionIVA)(((ComboEnumElement)cmbCondicionIVA.getSelectedItem()).getItem()) );
		proveedor.setCuit( txtCUIT.getText() );
		proveedor.setTieneCtaCte( chkCuentaCorriente.isSelected() );
		
		if( txtDescubierto.getValue()==null)
			txtDescubierto.setValue(0F);
			
		proveedor.setDescubierto( ((Number)txtDescubierto.getValue()).floatValue()  );
		proveedor.setDomicilioFacturacion( txtDomicilioFacturacion.getText() );
		proveedor.setObservaciones( txtObservaciones.getText() );
		
		proveedor.setFacebook( txtFacebook.getText() );
		proveedor.setTwitter( txtTwitter.getText() );
		proveedor.setLinkedin( txtLinkedin.getText() );
		proveedor.setPaginaWeb( txtWeb.getText() );
		
		return proveedor;
	}

	public void loadCombos(){
        //cargar tipos de documentos
        List tipos = new ArrayList();
       	for (TipoDocumento object : TipoDocumento.values()){
       		
       		ComboEnumElement tipo = new ComboEnumElement(object, I18nMessages.locale( object.getNombre() ));
			tipos.add(tipo);	
       	}
       	
        ComboModel model = new ComboModel();
        model.setElementos(tipos);
        cmbTipoDoc.setModel(model);
        cmbTipoDoc.setSelectedIndex(0);

        //cargar condiciones de iva
        List condiciones = new ArrayList();
       	for (CondicionIVA object : CondicionIVA.values()){
       		ComboEnumElement condicion = new ComboEnumElement(object, I18nMessages.locale( object.getNombre() ));
       		condiciones.add(condicion);	
       	
       	}
       	
        model = new ComboModel();
        model.setElementos(condiciones);
        cmbCondicionIVA.setModel(model);
        cmbCondicionIVA.setSelectedIndex(0);


    }
	private void initValidators() {
		
		required = new InputRequiredValidator(); 
		required.put(lblNombre, txtNombre, new JTextFieldInspector());
		required.setMessage(I18nMessages.INGRESE_REQUERIDOS);
		required.initialize();
		
	}

	
	public List<InputValidator> getValidators() {
		
		List<InputValidator> validators = new ArrayList<InputValidator>();
		
		validators.add( required );
		
		return validators;
	}

	public void clearInputs() {
		txtNombre.setText( "" );
		txtDomicilio.setText( "" );
		txtTelefonoFijo.setText( "" );
		txtMovil.setText( "" );
		txtNroDoc.setText( "" );
		txtEmail.setText( "" );
		txtContacto.setText( "" );
		txtCUIT.setText( "" );
		txtDomicilioFacturacion.setText( "" );
		txtObservaciones.setText( "" );
		txtFacebook.setText( "" );
		txtTwitter.setText( "" );
		txtLinkedin.setText( "" );
		txtWeb.setText( "" );
		pickerNacimiento.setDate( null );
		chkCuentaCorriente.setSelected(false);
		txtDescubierto.setValue(0F);
		jTabbedPane.setSelectedIndex(0);
	}

}
