/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.migestion.ui.swing.cuentasBancarias.panel;

import java.awt.Color;
import java.awt.Container;
import java.awt.Insets;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;

import javax.swing.JComponent;

import com.migestion.model.CuentaBancaria;
import com.migestion.model.Producto;
import com.migestion.swing.view.dialogs.adapters.IDialogAddAdapter;
import com.migestion.swing.view.dialogs.adapters.IDialogDeleteAdapter;
import com.migestion.swing.view.dialogs.adapters.IDialogUpdateAdapter;
import com.migestion.swing.view.dialogs.adapters.IDialogViewAdapter;
import com.migestion.swing.view.exceptions.ViewException;
import com.migestion.swing.view.inputs.InputFloatValidator;
import com.migestion.swing.view.inputs.InputIntegerValidator;
import com.migestion.swing.view.inputs.InputRequiredValidator;
import com.migestion.swing.view.inputs.InputValidator;
import com.migestion.swing.view.inputs.JFindObjectInspector;
import com.migestion.swing.view.inputs.JTextFieldInspector;
import com.migestion.ui.context.AppContext;
import com.migestion.ui.swing.i18n.I18nMessages;
import com.migestion.ui.swing.skin.ISkinForm;

/**
 *
 * @author bernardo
 */
public class CuentaBancariaPanel extends javax.swing.JPanel implements Serializable, IDialogAddAdapter, IDialogUpdateAdapter, IDialogViewAdapter, IDialogDeleteAdapter{

	private CuentaBancaria cuentaBancaria;
    private InputRequiredValidator required;
    private InputFloatValidator floatFormat;

	/**
     * Creates new form CuentaBancariaPanel
     */
    public CuentaBancariaPanel() {

    	initCuentaBancaria();
    	
        initComponents();
        
		initValidators();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBanco = new javax.swing.JLabel();
        lblNroCuenta = new javax.swing.JLabel();
        lblCBU = new javax.swing.JLabel();
        lblSucursal = new javax.swing.JLabel();
        lblTitular = new javax.swing.JLabel();
        lblCuit = new javax.swing.JLabel();
        lblSaldoInicial = new javax.swing.JLabel();
        lblObservaciones = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtNroCuenta = new javax.swing.JTextField();
        txtCBU = new javax.swing.JTextField();
        txtSucursal = new javax.swing.JTextField();
        txtTitular = new javax.swing.JTextField();
        txtCuit = new javax.swing.JTextField();
        scrollObservaciones = new javax.swing.JScrollPane();
        txtObservaciones = new javax.swing.JTextArea();
        txtSaldoInicial = new javax.swing.JFormattedTextField();

        lblBanco.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBanco.setText("Banco");

        lblNroCuenta.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNroCuenta.setText("Nro cuenta");

        lblCBU.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCBU.setText("CBU");

        lblSucursal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSucursal.setText("Sucursal");

        lblTitular.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTitular.setText("Titular");

        lblCuit.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCuit.setText("Cuit");

        lblSaldoInicial.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSaldoInicial.setText("Saldo inicial");

        lblObservaciones.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblObservaciones.setText("Observaciones");

        txtObservaciones.setColumns(20);
        txtObservaciones.setRows(5);
        scrollObservaciones.setViewportView(txtObservaciones);

        txtSaldoInicial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtSaldoInicial.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblObservaciones)
                    .addComponent(lblSaldoInicial)
                    .addComponent(lblCuit)
                    .addComponent(lblTitular)
                    .addComponent(lblSucursal)
                    .addComponent(lblCBU)
                    .addComponent(lblNroCuenta)
                    .addComponent(lblBanco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombre)
                    .addComponent(txtNroCuenta)
                    .addComponent(txtCBU)
                    .addComponent(txtSucursal)
                    .addComponent(txtTitular)
                    .addComponent(txtCuit)
                    .addComponent(scrollObservaciones, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                    .addComponent(txtSaldoInicial))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBanco)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNroCuenta)
                    .addComponent(txtNroCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCBU)
                    .addComponent(txtCBU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSucursal)
                    .addComponent(txtSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitular)
                    .addComponent(txtTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCuit)
                    .addComponent(txtCuit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSaldoInicial)
                    .addComponent(txtSaldoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblObservaciones)
                    .addComponent(scrollObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBanco;
    private javax.swing.JLabel lblCBU;
    private javax.swing.JLabel lblCuit;
    private javax.swing.JLabel lblNroCuenta;
    private javax.swing.JLabel lblObservaciones;
    private javax.swing.JLabel lblSaldoInicial;
    private javax.swing.JLabel lblSucursal;
    private javax.swing.JLabel lblTitular;
    private javax.swing.JScrollPane scrollObservaciones;
    private javax.swing.JTextField txtCBU;
    private javax.swing.JTextField txtCuit;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNroCuenta;
    private javax.swing.JTextArea txtObservaciones;
    private javax.swing.JFormattedTextField txtSaldoInicial;
    private javax.swing.JTextField txtSucursal;
    private javax.swing.JTextField txtTitular;
    // End of variables declaration//GEN-END:variables


	private void initCuentaBancaria() {
		
		this.cuentaBancaria = new CuentaBancaria();
		
	}



	public Container getDeleteMsgPanel() {
		
		this.setEditable( false );
		
		return this;
	}

	public Container getViewPanel() {
		
		this.setEditable( false );
		
		return this;
	}
	
	public void setEditable( Boolean editable ){
		
		txtNombre.setEditable( editable );
		txtNroCuenta.setEditable( editable );
		txtObservaciones.setEditable( editable );
		txtCBU.setEditable( editable );
		txtCuit.setEditable( editable );
		txtSaldoInicial.setEditable( editable );
		txtSucursal.setEditable( editable );
		
	}

	public void showObject(Object object) {
		
		cuentaBancaria = (CuentaBancaria)object;
		txtNombre.setText( cuentaBancaria.getNombre() );
		txtObservaciones.setText( cuentaBancaria.getObservaciones() );
		txtNroCuenta.setText( cuentaBancaria.getNroCuenta() );
		txtTitular.setText( cuentaBancaria.getTitular() );
		txtCBU.setText( cuentaBancaria.getCbu() );
		txtCuit.setText( cuentaBancaria.getCuit() );
		txtSucursal.setText( cuentaBancaria.getSucursal() );
		
		if( cuentaBancaria.getSaldoInicial()!=null)
			txtSaldoInicial.setValue( cuentaBancaria.getSaldoInicial() );
		
		txtSaldoInicial.setEnabled(false);
		
	}

	public Container getInputPanel() {
		return this;
	}

	public Object getObjectFromUI() throws ViewException {
		
		cuentaBancaria.setNombre( txtNombre.getText() );
		cuentaBancaria.setObservaciones( txtObservaciones.getText() );
		cuentaBancaria.setSucursal( txtSucursal.getText() );
		cuentaBancaria.setCbu( txtCBU.getText() );
		cuentaBancaria.setCuit( txtCuit.getText() );
		cuentaBancaria.setTitular( txtTitular.getText() );
		cuentaBancaria.setNroCuenta( txtNroCuenta.getText() );
		
		
		if(txtSaldoInicial.getText().length()>0)
			cuentaBancaria.setSaldoInicial( ((Number)txtSaldoInicial.getValue()).floatValue() );
		else
			cuentaBancaria.setSaldoInicial(0F);
		
		return cuentaBancaria;
	}

	private void initValidators() {
		
		required = new InputRequiredValidator(); 
		required.put(lblBanco, txtNombre, new JTextFieldInspector());
		required.put(lblSaldoInicial, txtSaldoInicial, new JTextFieldInspector());
		required.put(lblNroCuenta, txtNroCuenta, new JTextFieldInspector());
		required.put(lblTitular, txtTitular, new JTextFieldInspector());
		required.setMessage(I18nMessages.INGRESE_REQUERIDOS);
		required.initialize();
		
		floatFormat = new InputFloatValidator();
		floatFormat.put(lblSaldoInicial, txtSaldoInicial, new JTextFieldInspector());
		floatFormat.setMessage(I18nMessages.FORMATO_FLOAT_INVALIDO);
		floatFormat.initialize();
		
	}

	
	public List<InputValidator> getValidators() {
		
		List<InputValidator> validators = new ArrayList<InputValidator>();
		
		validators.add( required );
		validators.add( floatFormat );
		
		return validators;
	}

	public void clearInputs() {
		initCuentaBancaria();
		txtNombre.setText( "" );
		txtNroCuenta.setText( "" );
		txtObservaciones.setText( "" );
		txtCBU.setText( "" );
		txtCuit.setText( "" );
		txtSaldoInicial.setValue(null);
		txtSucursal.setText( "" );

	}


}