/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.migestion.ui.swing;

import com.migestion.model.Caja;
import com.migestion.model.EstadoCaja;
import com.migestion.model.Vendedor;
import com.migestion.swing.controller.exception.ControllerException;
import com.migestion.swing.custom.ComboModel;
import com.migestion.swing.model.UICollection;
import com.migestion.ui.context.AppContext;
import com.migestion.ui.criteria.UICajaCriteria;
import com.migestion.ui.service.UIServiceFactory;

/**
 *
 * @author bernardo
 */
public class PanelCajaDefault extends javax.swing.JPanel {

    /**
     * Creates new form PanelVendedorDefault
     */
    public PanelCajaDefault() {
        initComponents();
        
        
        loadCombo();
    }

    private void loadCombo() {
		try {

			UICajaCriteria criteria = new UICajaCriteria();
			criteria.addEstado( EstadoCaja.ABIERTA );
			UICollection cajasAbiertas = UIServiceFactory.getUICajaService().list( criteria );
			ComboModel model = new ComboModel();
	        model.setElementos(cajasAbiertas.getElements());
	        cmbCaja.setModel(model);
	        cmbCaja.setSelectedItem( AppContext.getInstance().getCajaDefault() );
	        
		} catch (ControllerException e) {
			e.printStackTrace();
		}
		
	}

	/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelVendedor = new javax.swing.JPanel();
        lblCaja = new javax.swing.JLabel();
        cmbCaja = new javax.swing.JComboBox();

        setLayout(new java.awt.BorderLayout());

        java.awt.GridBagLayout jPanelDatosPersonalesLayout = new java.awt.GridBagLayout();
        jPanelDatosPersonalesLayout.columnWidths = new int[] {20, 50, 334, 20};
        jPanelVendedor.setLayout(jPanelDatosPersonalesLayout);

        lblCaja.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCaja.setText("Caja");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 17;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        jPanelVendedor.add(lblCaja, gridBagConstraints);

        cmbCaja.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbCaja.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cmbCajaPropertyChange(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanelVendedor.add(cmbCaja, gridBagConstraints);

        add(jPanelVendedor, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbCajaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cmbCajaPropertyChange
        
        Caja caja = (Caja)cmbCaja.getSelectedItem();
        if( caja != null )
            AppContext.getInstance().setCajaDefault(caja);
        
    }//GEN-LAST:event_cmbCajaPropertyChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbCaja;
    private javax.swing.JPanel jPanelVendedor;
    private javax.swing.JLabel lblCaja;
    // End of variables declaration//GEN-END:variables
}
