/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.migestion.ui.swing;

import com.migestion.model.Sucursal;
import com.migestion.swing.controller.exception.ControllerException;
import com.migestion.swing.custom.ComboModel;
import com.migestion.swing.model.UICollection;
import com.migestion.ui.context.AppContext;
import com.migestion.ui.criteria.UISucursalCriteria;
import com.migestion.ui.service.UIServiceFactory;

/**
 *
 * @author bernardo
 */
public class PanelSucursalDefault extends javax.swing.JPanel {

    /**
     * Creates new form PanelVendedorDefault
     */
    public PanelSucursalDefault() {
        initComponents();
        
        
        //loadCombo();
    }

    private void loadCombo() {
		try {

			UISucursalCriteria criteria = new UISucursalCriteria();
			UICollection sucursales = UIServiceFactory.getUISucursalService().list( criteria );
			ComboModel model = new ComboModel();
	        model.setElementos(sucursales.getElements());
	        cmbSucursal.setModel(model);
	        cmbSucursal.setSelectedItem( AppContext.getInstance().getSucursalDefault() );
	        
		} catch (ControllerException e) {
			e.printStackTrace();
		}
		
	}

	/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelVendedor = new javax.swing.JPanel();
        lblCaja = new javax.swing.JLabel();
        cmbSucursal = new javax.swing.JComboBox();

        setLayout(new java.awt.BorderLayout());

        java.awt.GridBagLayout jPanelDatosPersonalesLayout = new java.awt.GridBagLayout();
        jPanelDatosPersonalesLayout.columnWidths = new int[] {20, 50, 334, 20};
        jPanelVendedor.setLayout(jPanelDatosPersonalesLayout);

        lblCaja.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCaja.setText("Sucursal");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 17;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        jPanelVendedor.add(lblCaja, gridBagConstraints);

        cmbSucursal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbSucursal.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cmbSucursalPropertyChange(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanelVendedor.add(cmbSucursal, gridBagConstraints);

        add(jPanelVendedor, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbSucursalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cmbSucursalPropertyChange
        // TODO add your handling code here:
        
    	Sucursal sucursal = (Sucursal)cmbSucursal.getSelectedItem();
        if( sucursal != null )
            AppContext.getInstance().setSucursalDefault(sucursal);
        
    }//GEN-LAST:event_cmbSucursalPropertyChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbSucursal;
    private javax.swing.JPanel jPanelVendedor;
    private javax.swing.JLabel lblCaja;
    // End of variables declaration//GEN-END:variables
}
