/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.migestion.ui.swing;

import com.migestion.model.EstadoCaja;
import com.migestion.swing.controller.exception.ControllerException;
import com.migestion.swing.custom.ComboModel;
import com.migestion.swing.model.UICollection;
import com.migestion.ui.context.AppContext;
import com.migestion.ui.criteria.UICajaCriteria;
import com.migestion.ui.criteria.UISucursalCriteria;
import com.migestion.ui.criteria.UIVendedorCriteria;
import com.migestion.ui.service.UIServiceFactory;

/**
 *
 * @author bernardo
 */
public class PanelMenuToolbar extends javax.swing.JPanel {

    /**
     * Creates new form PanelMenuToolbar
     */
    public PanelMenuToolbar() {
        initComponents();
        
        loadCombos();
    }

    private void loadCombos() {
		try {

			UISucursalCriteria criteria = new UISucursalCriteria();
			UICollection sucursales = UIServiceFactory.getUISucursalService().list( criteria );
			ComboModel model = new ComboModel();
	        model.setElementos(sucursales.getElements());
	        cmbSucursal.setModel(model);
	        cmbSucursal.setSelectedItem( AppContext.getInstance().getSucursalDefault() );
	        
		} catch (ControllerException e) {
			e.printStackTrace();
		}
		
		try {

			UIVendedorCriteria criteria = new UIVendedorCriteria();
			UICollection vendedores = UIServiceFactory.getUIVendedorService().list( criteria );
			ComboModel model = new ComboModel();
	        model.setElementos(vendedores.getElements());
	        cmbVendedor.setModel(model);
	        cmbVendedor.setSelectedItem( AppContext.getInstance().getVendedorDefault() );
	        
		} catch (ControllerException e) {
			e.printStackTrace();
		}

		try {

			UICajaCriteria criteria = new UICajaCriteria();
			criteria.addEstado( EstadoCaja.ABIERTA );
			UICollection cajasAbiertas = UIServiceFactory.getUICajaService().list( criteria );
			ComboModel model = new ComboModel();
	        model.setElementos(cajasAbiertas.getElements());
	        cmbCaja.setModel(model);
	        cmbCaja.setSelectedItem( AppContext.getInstance().getCajaDefault() );
	        
		} catch (ControllerException e) {
			e.printStackTrace();
		}

	}

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCombos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbCaja = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cmbVendedor = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        cmbSucursal = new javax.swing.JComboBox();
        panelInicio = new javax.swing.JPanel();
        btnInicio = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        panelCombos.setLayout(new java.awt.GridBagLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Caja");
        jLabel1.setPreferredSize(new java.awt.Dimension(50, 18));
        panelCombos.add(jLabel1, new java.awt.GridBagConstraints());

        cmbCaja.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelCombos.add(cmbCaja, new java.awt.GridBagConstraints());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Vendedor");
        jLabel2.setPreferredSize(new java.awt.Dimension(90, 18));
        panelCombos.add(jLabel2, new java.awt.GridBagConstraints());

        cmbVendedor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelCombos.add(cmbVendedor, new java.awt.GridBagConstraints());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Sucursal");
        jLabel3.setPreferredSize(new java.awt.Dimension(80, 18));
        panelCombos.add(jLabel3, new java.awt.GridBagConstraints());

        cmbSucursal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelCombos.add(cmbSucursal, new java.awt.GridBagConstraints());

        add(panelCombos, java.awt.BorderLayout.LINE_END);

        panelInicio.setLayout(new java.awt.BorderLayout());

        btnInicio.setText("Inicio");
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        panelInicio.add(btnInicio, java.awt.BorderLayout.CENTER);

        add(panelInicio, java.awt.BorderLayout.LINE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInicioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInicio;
    private javax.swing.JComboBox cmbCaja;
    private javax.swing.JComboBox cmbSucursal;
    private javax.swing.JComboBox cmbVendedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel panelCombos;
    private javax.swing.JPanel panelInicio;
    // End of variables declaration//GEN-END:variables
}
