/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.migestion.ui.swing.cuentasBancarias.movimientos.panel;

import javax.swing.ComboBoxModel;
import javax.swing.JPanel;

import com.migestion.model.CuentaBancaria;
import com.migestion.swing.controller.exception.ControllerException;
import com.migestion.swing.custom.ComboModel;
import com.migestion.swing.model.UICollection;
import com.migestion.swing.search.criteria.UICriteria;
import com.migestion.swing.view.dialogs.ICriteriaPanel;
import com.migestion.swing.view.exceptions.ViewException;
import com.migestion.ui.context.AppContext;
import com.migestion.ui.context.observers.listeners.ICuentaBancariaListener;
import com.migestion.ui.criteria.UICuentaBancariaCriteria;
import com.migestion.ui.criteria.UIMovimientoCuentaBancariaCriteria;
import com.migestion.ui.service.UIServiceFactory;

/**
 *
 * @author bernardo
 */
public class UIMovimientoCuentaBancariaCriteriaPanel extends javax.swing.JPanel  implements ICriteriaPanel, ICuentaBancariaListener{

	
    /**
     * Creates new form UIPagoCriteriaPanel
     */
    public UIMovimientoCuentaBancariaCriteriaPanel() {

    	initComponents();

    	AppContext.getInstance().getCuentaBancariaObserver().addListener(this);
    	
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCuenta = new javax.swing.JLabel();
        cmbCuentas = new javax.swing.JComboBox();
        lblFecha = new javax.swing.JLabel();
        pickerFecha = new com.toedter.calendar.JDateChooser();

        lblCuenta.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCuenta.setText("Cuenta bancaria");

        cmbCuentas.setModel( getCuentasBancariasModel() );
        cmbCuentas.setSelectedIndex(0);

        lblFecha.setText("Fecha");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFecha)
                    .addComponent(lblCuenta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbCuentas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pickerFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 130, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbCuentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(pickerFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFecha))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbCuentas;
    private javax.swing.JLabel lblCuenta;
    private javax.swing.JLabel lblFecha;
    private com.toedter.calendar.JDateChooser pickerFecha;
    // End of variables declaration//GEN-END:variables
	
    
    
	public UICriteria getCriteria() throws ViewException{
		
		UIMovimientoCuentaBancariaCriteria criteria = new UIMovimientoCuentaBancariaCriteria();

		CuentaBancaria cuentaBancaria = (CuentaBancaria)cmbCuentas.getSelectedItem();
		
		if( cuentaBancaria == null )
			throw new ViewException("Debe seleccionar una cuenta bancaria");
		
//		if( pickerFecha.getDate() == null )
//			throw new ViewException("Debe seleccionar una fecha");
		
		criteria.setCuentaBancaria( cuentaBancaria );
		criteria.setFecha( pickerFecha.getDate() );
	
		criteria.setPaginable(true);
		return criteria;

	}

	public void setCriteria(UICriteria criteria) {
		
		cmbCuentas.setSelectedItem( ((UIMovimientoCuentaBancariaCriteria)criteria).getCuentaBancaria() );
		pickerFecha.setDate( ((UIMovimientoCuentaBancariaCriteria)criteria).getFecha() );
		
	}


	public JPanel getPanel() {
		return this;
	}

    private ComboBoxModel getCuentasBancariasModel() {
        ComboModel model = new ComboModel();
		
		 try {
		
			 UICuentaBancariaCriteria criteria = new UICuentaBancariaCriteria();
			 UICollection cuentas =	 UIServiceFactory.getUICuentaBancariaService().list( criteria );
			 model.setElementos(cuentas.getElements());
		
		 } catch (ControllerException e) {
			 e.printStackTrace();
		 }		

		 return model;
    }

	public void objectCreated(CuentaBancaria objectCreated) {
		Object selected = cmbCuentas.getSelectedItem();
		cmbCuentas.setModel( getCuentasBancariasModel() );
        cmbCuentas.setSelectedItem(selected);
	}

	public void objectDeleted(CuentaBancaria objectDeleted) {
		Object selected = cmbCuentas.getSelectedItem();
		cmbCuentas.setModel( getCuentasBancariasModel() );
        cmbCuentas.setSelectedItem(selected);
	}

	public void objectUpdated(CuentaBancaria objectUpdated) {
		Object selected = cmbCuentas.getSelectedItem();
		cmbCuentas.setModel( getCuentasBancariasModel() );
        cmbCuentas.setSelectedItem(selected);
	}
}
