/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.migestion.ui.swing.pagos.dialog;

/**
 *
 * @author bernardo
 */
public class PanelAddDetallesFormaPago extends javax.swing.JPanel {

    
    
    /**
     * Creates new form PanelAddDetallesFormaPago
     */
    public PanelAddDetallesFormaPago() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHeader = new javax.swing.JPanel();
        btnAgregarDetalle = new javax.swing.JButton();
        panelDetalles = new javax.swing.JPanel();
        scrollDetalles = new javax.swing.JScrollPane();
        tableDetalles = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        btnAgregarDetalle.setText("Agregar detalle");
        btnAgregarDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarDetalleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAgregarDetalle)
                .addContainerGap(524, Short.MAX_VALUE))
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAgregarDetalle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(panelHeader, java.awt.BorderLayout.PAGE_START);

        panelDetalles.setLayout(new java.awt.BorderLayout());

        tableDetalles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollDetalles.setViewportView(tableDetalles);

        panelDetalles.add(scrollDetalles, java.awt.BorderLayout.CENTER);

        add(panelDetalles, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarDetalleActionPerformed
        // TODO add your handling code here:
        //TODO llamar al diálogo para seleccionar una forma de pago
        //y luego abrir la ventana de acuerdo a la forma de pago
        //que sea modal así a la vuelta tengo el detalle creado
        //para agregar al listado.
       // DialogSeleccionarFormaPago dialogFormaPago = new DialogSeleccionarFormaPago(, true);
    }//GEN-LAST:event_btnAgregarDetalleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarDetalle;
    private javax.swing.JPanel panelDetalles;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JScrollPane scrollDetalles;
    private javax.swing.JTable tableDetalles;
    // End of variables declaration//GEN-END:variables
}
